Try to generate client for the user service in the gateway
This fails due to `java.lang.NoClassDefFoundError: Could not initialize
class graphql.parser.antlr.GraphqlLexer`